import "../styles/globals.css";

export const metadata = {
  title: "Big Dart E-Commerce",
  description: "Generated by create next app",
  applicationName: "Next.js",
  referrer: "origin-when-cross-origin",
  keywords: ["Next.js", "React", "JavaScript"],
  authors: [{ name: "Seb" }, { name: "berk", url: "https://nextjs.org" }],
  colorScheme: "light",
  viewport: "width=device-width, initial-scale=1",
  creator: "BMG",
  publisher: "Berk M. Gyuler",
  locale: "en-US",
  type: "website",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head className="scroll-smooth hover:scroll-auto"></head>
      <body>{children}</body>
    </html>
  );
}
